### ISSUE TITLE
Defining relationships and filter parameters for agent-based queries

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#15]
I made some assertion somewhere in the past that minimizing the number of links between resources as well as maximizing the flexibility of those links seemed like a good general rule of thumb.

In the current schema, we have a lot of this sort of thing:

    inventoriedEconomicResources(resourceClassification: URL, page: Int): [EconomicResource]
    searchInventoriedEconomicResources(searchString: String): [EconomicResource]

My intention is to merge all these relationship groups together into single fields (in the above case, `inventoriedEconomicResources`) and provide all parameters as options to a single resolver. Does this sound like the correct approach?

**Comment by fosterlynn** [comment]
>My intention is to merge all these relationship groups together into single fields (in the above case, inventoriedEconomicResources) and provide all parameters as options to a single resolver. Does this sound like the correct approach?

Sounds good to me.  (It all developed as a happening, happy to have more eyes on the cleanup!)

**Comment by pospi** [comment]
@fosterlynn RE previous commit & the `input` types at the top of the Agent module, I think we need to define what "related" means in each context. eg. for `Process`es is it any process the agent is a `workingAgent` on, ones they have authored, ones they have made commitments to etc- or do we need multiple search fields to disambiguate that?

We also need to define for each case which fields the `searchString` indexes.

Let me know if it's best to create separate issues for all these or keep the discussion going in here and we can adjust accordingly (:

**Comment by pospi** [comment]
Going a bit deeper, it seems like `Agent` is the main part of the system where this kind of thing needs thinking through. All of the relationships between other entities seem relatively straightforward and sufficiently granular- it's agent-based queries that form up most use-cases, e.g. *"I want to be able to find all the intents which I have contributed to"*. Will rename this issue accordingly.

**Comment by fosterlynn** [comment]
>Going a bit deeper, it seems like Agent is the main part of the system where this kind of thing needs thinking through.

Yes, that was my experience.  Most information needed for a UI is either what you as a person are involved in; or what a project or organization has going on.

Looking in Agent - we can probably get rid of year and month on Plan.

>for Processes is it any process the agent is a workingAgent on, ones they have authored, ones they have made commitments to etc- or do we need multiple search fields to disambiguate that?

Good question, don't know.  Probably don't need multiple search fields, although it might be slightly different logic for person and organization agents.  Do you think we should specify the results?  Probably wouldn't hurt.

**Comment by fosterlynn** [comment]
Also, I'm a bit confused by the things at the top of Agent spec vs the ones inside?

**Comment by pospi** [comment]
Could we get rid of year & month on all queries, and provide generic date range parameters instead?

RE *"top of Agent spec vs. inside"*- the stuff at the top is input object types defining how to query other things relative to any agent. The stuff inside is the core schema for the `Agent` type(s). But yes- it all ends up inside at the end of the day, it's just an awkward part of the syntax in that you need to define it this way.

**Comment by fosterlynn** [comment]
>Could we get rid of year & month on all queries, and provide generic date range parameters instead?

Yes, please.

**Comment by pospi** [comment]
There is a great set of user-level requirements for these relationships (and more) at https://github.com/holo-rea/holo-rea/issues/34

**Comment by pospi** [comment]
All good information contained herein, being factored into further conversations.
