### ISSUE TITLE
Property descriptions

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/vf-graphql#17]
The system of record for descriptions of classes/types and properties is https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL.  So let's make all the descriptions in the graphql reference match that file.  I think I changed the type definitions earlier.  I noticed descriptions added to the properties, those will need to get changed too.

The descriptions in the turtle file are thought through to one degree or another, it is a mixed bag.  So if anyone wants to change a definition, I'd suggest a PR to the .ttl file in the VF repo, then once approved, we change it here.

After we get in sync, I'll take responsibility for making changes here in the graphql reference whenever anything (names, definitions, whatever) gets changed in the formal VF definition.

**Comment by fosterlynn** [comment]
Another thought: can we comment them with # instead of the way they are done now?  Or maybe put them all in the type definition?  Some way to make the thing more readable, any suggestion welcome.... not sure how they show up in things that use the reference like the thing you posted in HoloREA chat @pospi ....

**Comment by pospi** [comment]
Yeah I'm not fond of that either, but I've found single-line string literals work too. For most of the descriptions those are probably more readable- https://stackoverflow.com/a/39963267/141881

Looks like using comments for this is no longer the de-facto standard, and probably won't work with all tooling.

**Comment by fosterlynn** [comment]
OK, let's do it in the most standard way.

**Comment by pospi** [comment]
It strikes me that there is opportunity for additional expressiveness in how we describe these properties in GraphQL vs. RDF. Namely things like action, which [have the same descriptions in every domain](https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL#L143). Would it be possible / worthwhile in the RDF spec to declare a different description for an `EconomicEvent`'s `action` vs a `RecipeFlow`'s `action`, etc? If not possible, should we do this in the GraphQL version?

**Comment by pospi** [comment]
Thinking on it more, it's possible this is the reason there is usually confusion when newcomers are trying to understand these three layers- the properties of the records are all described in very abstract terms which do not apply very concretely to Event/Commitment/Intent, so consequently it's hard to understand what role inputs/outputs/providers/receivers/resourceClassifications play in each context.

**Comment by fosterlynn** [comment]
>Would it be possible / worthwhile in the RDF spec to declare a different description for an EconomicEvent's action vs a RecipeFlow's action, etc? If not possible, should we do this in the GraphQL version?

No.  An action is an action.  Of course since RecipeFlow, Intent, Commitment, EconomicEvent are different things themselves, there will be some different implications.  But if you intend or commit to `work`, you will probably do `work`.  If you intend or commit to `produce` some things, you will probably `produce` some things.  You'll notice most of the properties follow in the same way.

**Comment by pospi** [comment]
Ok. Just to be sure, since we might be miscommunicating. I'm talking about the `owl:ObjectProperty` (lowercase), not the `owl:Class`.

Current description is *"relates a process input or output to a verb, such as consume, produce, work, improve, etc."*. I would find it easier to understand the model if it were something like *"defines the verb which was undertaken in this observed event"* when `rdfs:domain == vf:EconomicEvent`; *"defines the verb planned to be enacted in future when the intent has been met"* when `rdfs:domain == vf:Intent` and so on. It's a general complaint I have with the model not being terribly grounded in reality, but perhaps adding more examples to the documentation could also alleviate that.

**Comment by fosterlynn** [comment]
>I would find it easier to understand the model if it were

Well, how about if we start with the VF definitions, which imo we should keep in sync?  And then add on another sentence of specifics since we can do that in graphql where the same property appears multiple times?

Of course the VF definitions can always be improved too, some have had some work and some were more tossed off in a hurry. Let's take that through the VF/VF repo, and filter changes back to the graphql.

And we agree with you that more examples will help a lot, we do need to focus some on that.  We have a lot in process.

**Comment by pospi** [comment]
Happy with this.. specific issues logged for particular properties.
