### ISSUE TITLE
EconomicResource url

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#19]
What's the purpose of this field? I notice that it is the only record which has a `url` field on it... maybe it's legacy stuff from LOD-land, from when URLs and IDs were semi-synonymous?

**Comment by fosterlynn** [comment]
It is legacy, but I think from earlier, it isn't a URL / ID confusion.  We can get rid of it.  It's on the graphql but not in VF anyhow.  I think we still have URL on ResourceSpecification, where I can see it might be useful, but don't really know, so don't care if we keep it there or not.

**Comment by pospi** [comment]
done!
