### ISSUE TITLE
Verify `inScopeOf`

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#20]
I've gone through and put this on basically every object except for `Agent`s & their role-based records. Just confirming that's correct, and that it *should* be applied to things like `ResourceSpecification`, which may not be things we'd want to limit by scope.

If it all looks good you can just close this issue (;

**Comment by fosterlynn** [comment]
One point of clarification: inScopeOf is optional.  And the UML diagram is a good reference for things that have a range of owl:Thing in the rdf spec, but really don't apply to anything and everything. 

Imo, it should be in Process, Intent, Commitment, EconomicEvent.  And I just added it to Claim in the UML, which is a new entity, and I missed it there.  So we can take it out of ResourceSpecification.  (OCP needed it for 'some things didn't get done as they needed to be' reasons.  We may still be missing something there, but the model should be different than OCP, and may not ever rise to the level of the vocabulary, not sure.)

**Comment by fosterlynn** [comment]
As part of the last PR, I removed it from where I didn't think it was needed.

**Comment by pospi** [comment]
So, we can take `inScopeOf` out of `Fulfillment` & `Satisfaction`, and presume that access to those resources is not allowed if the given linked `EconomicEvent` / `Commitment` / `Intent` doesn't have the appropriate scope?

I think `Transfer` needs it too. `Plan` & `Agreement`? Not sure. `RecipeProcess` & `RecipeFlow` probably need it, don't they? Basically all the 'flow' records. And I do think `Resource` needs to have one, selective exposure of different resources seems to be a common use-case.

**Comment by pospi** [comment]
Will probably leave https://github.com/valueflows/vf-graphql/pull/23 unmerged until we land on this one

**Comment by fosterlynn** [comment]
>So, we can take inScopeOf out of Fulfillment & Satisfaction, and presume that access to those resources is not allowed if the given linked EconomicEvent / Commitment / Intent doesn't have the appropriate scope?

Yes, the scope would follow from those base entities.  But, I hadn't thought of it affecting access in such a direct way.  Possibly a topic for a whole separate discussion.  And possibly something that will be configurable by the agents and/or app specific.  Or maybe this could make sense as a general access rule, not sure.

>I think Transfer needs it too. Plan & Agreement? Not sure. RecipeProcess & RecipeFlow probably need it, don't they? Basically all the 'flow' records. And I do think Resource needs to have one, selective exposure of different resources seems to be a common use-case.

Transfer needs it if it stays, which is doubtful atm, so I didn't bother.  Plans can cross scopes if the scopes are related or have agreements - making it very useful for coordination between agents.  Agreements will be part of at least 2 scopes, based on the parties to the agreement.  RecipeProcess might need it if an agent needs to know what recipes they are using.  But when we add versioning and forking to recipes, I think it will land in a different place in the recipe model.  Also, I think of recipes in general as open shared knowledge.  RecipeFlow, no, just part of a recipe.  EconomicResource can have different kinds of rights and responsibilities for it, so is not so simple as adding a scope to it to denote ownership, we're working on some of that.  And scope doesn't exactly mean ownership.

Thinking of scope as part of what you might need to filter to do accounting for a group agent is one general way to conceptualize it, although it might sometimes apply more broadly, say accounting for an ecosystem.  Another way is to think about it is what might need to be shown in an operational app for a group agent.  And for some things, you will also need provider and receiver agents to filter for accounting.

More to say about that, and probably there is not agreement within VF.  I still plan to create an issue to re-discuss scope, and consider limiting the domain and range in the vocabulary itself, and limiting the definition further.  Not necessarily a high priority though.

**Comment by pospi** [comment]
Updated https://github.com/valueflows/vf-graphql/pull/23 per these changes & merged.

Re conceptualising scope: how does the idea of https://github.com/holo-rea/holo-rea/issues/9#issuecomment-487804467 sound to you RE its relationship to network visibility?

I don't have `Agreement` in here, only `ExchangeAgreement` - same thing?

**Comment by fosterlynn** [comment]
>I don't have Agreement in here, only ExchangeAgreement - same thing?

Probably we'll get rid of ExchangeAgreement and just use Agreement.  But not decided yet.
