### ISSUE TITLE
Define top-level query filter criteria for reporting

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#22]
As per #21, queries are also in an incomplete state as were pulled from NRP's partial coverage to begin with.

We need a good set of user stories linked to this epic describing the types of UI bindings and reporting queries that we need from the system.

We also need to decide on the information architecture of the query API. My choice would be that all parameters are logical 'AND's and are available on every `all*` query endpoint that necessitates them. We should thus delete `filteredEconomicEvents` and move those parameters to `allEconomicEvents` for consistency (which is fine, nobody is using that code yet). Basically, a search with no args = an "all" query.

The goal is to end up with the smallest number of most generic parameters possible, because every parameter added needs to be implemented in every system that wants to provide ValueFlows data in order to be compliant; and that takes time & effort.

**Comment by pospi** [comment]
This is related to #15, which is where all the queries with an agent context are defined. The same types of sub-queries need to be fleshed out for all record types where there are use-cases for filtering against 1:many relationships.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/22.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
