### ISSUE TITLE
Finalise schema for agreements

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#26]
Currently the codebase has `ExchangeAgreement`, but not `Agreement`, which keeps getting mentioned. These are parts of external vocabularies, but which ones? We (probably) need to bring the fields into GraphQL for completeness. And I'm unsure whether `Agreement` is the only record we should have, or if both `Agreement` & the more specific `ExchangeAgreement` are needed?

I also note that the current status of GraphQL is that:

- `EconomicEvent`s, `Commitment`s, & `Intent`s can be created under an agreement
- `Fulfillment`s can be created under agreements, but `Satisfaction`s cannot
- `Transfer`s can't be created under an agreement, but it looks like they should be able to

**Comment by fosterlynn** [comment]
Created this PR https://github.com/valueflows/vf-graphql/pull/27.  I think that will do it for this round of development.  There is no new info about other vocabularies for Agreement.  Let's see what we end up needing for new user groups.

>EconomicEvents, Commitments, & Intents can be created under an agreement

correct

>Fulfillments can be created under agreements, but Satisfactions cannot

Good catch, I'm taking it off of Fulfillment.

>Transfers can't be created under an agreement, but it looks like they should be able to

Both Transfers and Processes are sort of orthogonal, the flows can carry the relationships to agreement. Anyhow, Transfer will probably get merged into Process.

**Comment by fosterlynn** [comment]
Also, just to clarify the `under` references:  Those are more for explaining why something is how it is (calculation, etc.).  Mostly those will be already existing agreements.  The new ones `clauseOf` and `realizationOf` are more part of the actual model, and for those, an Agreement will be created as part of the VF processing.

**Comment by fosterlynn** [comment]
>Also, just to clarify the under references

Actually, I'm thinking about this a bit more.  I think I would like to get rid of the under reference to vf:Agreement, and just leave it more general, just referencing whatever agreement is out there somewhere.  Leaving vf:Agreement something that is created as part of the VF processing.  (And eventually extensions like distribution agreement.)  I'll do a PR in VF and see what happens.  in the meantime, this is still an improvement.

**Comment by fosterlynn** [comment]
> I'll do a PR in VF and see what happens.

Did the PR.  But thinking a bit further, I'm going to take this out of the graphql reference irrespective of what we decide in VF, since mostly there won't be anything to reference of class Agreement.  Will do so on the existing PR, https://github.com/valueflows/vf-graphql/pull/27.

**Comment by pospi** [comment]
I've updated some of that PR so that `under` can reference an `Agreement` or external `URL`, and it's clear which of the two it's pointing to. This meant adding extra mutation parameters, which I'm not the biggest fan of but it's probably the simplest way forward.

Also- do we think `Intent`s have a bearing on how agreements are formed up & completed? Or in those cases is the relationship loose and covered by `under`?

I can see why this is a hotly debated part of the spec.... should `Agreement` just collapse into `Process` in the same way as `Transfer`? My gut feeling is it's nice to be able to distinguish all 3 explicitly at the "top level" of the vocab... i.e. not having to dig into the `Process.classifiedAs` to differentiate. But there may be cases where that makes queries *more* complex, too. Likely to be tradeoffs either way...

**Comment by fosterlynn** [comment]
>I've updated some of that PR so that under can reference an Agreement or external URL, and it's clear which of the two it's pointing to. 

Curious, why do you think we need that?  I agree things are a bit obscure.  But I think the VF Agreement will need to be fairly specifically defined.

>Also- do we think Intents have a bearing on how agreements are formed up & completed? Or in those cases is the relationship loose and covered by under?

Yes, Intents can lead to agreements, through Proposals, which we're trying to get into VF at least in some minimum form, but its not there yet.  Proposals are the publishing of intents, possibly with reciprocal intents.  It is here https://github.com/valueflows/valueflows/pull/503. 

> should Agreement just collapse into Process in the same way as Transfer?

No.  Agreement combines 2 directions of flows (or more).  Process and Transfer are one way flows.  I can find some somewhat lousy pictures I made in the past, or explain more if this isn't clear.

We haven't actually decided to collapse Transfer into Process either. I prefer not but offered it as a compromise to get things moving - but the whole Transfer thing is not complete, it is a hard model with a bunch of trade-offs.  And to be clear, there are some advantages of that collapse too, I'm getting a bit more fond of it. And will be happy either way.  Anyhow, I think on this one, we need to wait until the VF side can get it figured out.

**Comment by pospi** [comment]
Ok, mostly all good then.

RE "under": it just made sense for me. I figured anything that could be "under an agreement" would want to be able to reference an agreement defined within the same VF system as well as arbitrary external ones. Did I assume wrong?

**Comment by fosterlynn** [comment]
>RE "under": it just made sense for me. I figured anything that could be "under an agreement" would want to be able to reference an agreement defined within the same VF system as well as arbitrary external ones. Did I assume wrong?

Well, on this one I've been giving you my opinion based on my experience.  I don't think we have consensus in VF about it at all really.  So let's leave it however it is now, or however you prefer, and work it through VF.  I do think it is worth spending some effort to keep things as simple as possible though, which I'll take on over in VF in those discussions.

**Comment by pospi** [comment]
Ok! Are we happy with this PR and ready to merge as-is, then?

**Comment by fosterlynn** [comment]
>Ok! Are we happy with this PR and ready to merge as-is, then?

good enough for now :)

**Comment by pospi** [comment]
Closing / merging this but noting that `Agreement` schema is considered... semi-stable?

**Comment by fosterlynn** [comment]
>but noting that Agreement schema is considered... semi-stable?

I wouldn't consider it that actually, sorry. Needs to be used in a real situation as currently defined.
