### ISSUE TITLE
Finalise schema for locations

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#28]
Probably based on this vocab: https://www.w3.org/2017/sdwig/bp/#c-spatialdatavoc

**Comment by pospi** [comment]
@elf-pavlik if this is the vocab we're most likely to use, that's all I need to know- I can pull out the core fields from there and we can do a little back and forth to verify (:

**Comment by fosterlynn** [comment]
@pospi  if you want to give it a whirl, cool!  If you read that doc closely, the location vocab is not consolidated, there are 3 vocabs which we will need to pick from, so it will be a little work.  That said, we probably don't need much to start:
* address of some sort, hopefully just text
* longitude
* latitude
* altitude (from my experience in modeling location for a newspaper a few decades ago, but maybe going too far to start with)

Probably at some point we'll need polygons or whatever they use to define regions?

cc @elf-pavlik  (I'm thinking you seem too busy to tackle this one now although you mentioned it earlier?)

**Comment by pospi** [comment]
Cool, that is basically what is there already. I might just make `address` non-required; so that groups can put "internal" locations down without having to add empty addresses.

And to confirm, `agent.primaryLocation` is not meant to be a full location object, just a string- correct?

**Comment by fosterlynn** [comment]
>And to confirm, agent.primaryLocation is not meant to be a full location object, just a string- correct?

Hmmm.  I think if we put Location into VF, we should make agent.primaryLocation and resource.currentLocation reference Locations.  We should be fairly compliant with any location thingies, do you think?  And agents can define a bunch of their own locations as needed, like within a warehouse or whatever.  And all properties on Location should be optional imo, at the risk of having some that aren't mappable - what do you think?

Also, I didn't mention we should probably have "name" and "note" on Location too, but those won't need to come from a location vocabulary like the ones @elf-pavlik referenced.  Or I suppose they could if there is something pretty standard out there?

**Comment by pospi** [comment]
Done. I also went ahead and added `observedLocation` to `EconomicEvent`, because per https://github.com/valueflows/valueflows/issues/486 it looks like we have consensus that it's a good idea to include the field; just leaving it open-ended as to the exact schema.

**Comment by fosterlynn** [comment]
ref https://github.com/valueflows/valueflows/pull/510 in process
