### ISSUE TITLE
rename `URL` type to `URI`

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#33]
This seems like a good idea... seems sensible to indicate that any resolvable URI can be used with these fields, including web URLs but also Holochain resource URIs, SSB content URIs etc.

I'm not actually sure if this affects anything other than code I am about to write just yet, but if it's named this way in the base VF spec too then we might want to make the change there as well. It could be something only present in the GraphQL version.

**Comment by fosterlynn** [comment]
Seems good to me.  Go for it, and I'll do a PR in main VF.
