### ISSUE TITLE
Self-explanatory documentation for new intent quantity fields

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#39]
Going through wiring up `Intent` now and the new `flowQuantity` field is not documented. Not sure I fully understand `unitQuantity` and `availableQuantity` either, would be good to have a pointer to the detailed explanations of those!

**Comment by fosterlynn** [comment]
I'll update the doc and do a PR

**Comment by fosterlynn** [comment]
Briefly though, `flowQuantity` is for if your intent is for a specific quantity, like "I need 10 liters of oil"; works like the quantities in commitment and event.  `unitQuantity` is for price list scenarios, or much of e-commerce, like "I'm offering 25# cases of apples, you can buy how ever many you need, usually."  `availableQuantity` we may not need very much, but it does appear on Amazon for example, and it appears on the UI for DirectHarvest stuff.  I'm Ok having it or not at this point.

**Comment by pospi** [comment]
These look great in latest PRs
