### ISSUE TITLE
First pass updates

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#5]
I managed to find the time to look through your VF schema updates today. All seems pretty straightforward.

I will go through and change a lot of your `Int` -> `String` changes to `ID` at some point- that field type has some extra benefits and also doesn't care whether the input is a string or int- convenient! It's nice to have a struct for time periods too, but at first glance maybe we need to split that into times & periods? It seems like the same type is being used for both. And I can figure out union types for the track/trace queries too, as well as some inheritance stuff to keep it DRY.

Some things look like they don't yet do much (like `ExchangeAgreement`), was the idea to stub them and have me go through and fill in fields as I get up to speed with the latest spec? Also curious why so many things in the knowledge schema have been commented out.

Unrelated, but I think the best way forward is to merge all the query-like relationships into single relationships- it seems reasonable to me to aim for the fewest number of edges between nodes, but to have those edges as flexible as possible. I think the filter parameters in such edges are always ANDed together- if you want OR, you can use field aliasing [like this](https://github.com/hasura/graphql-engine/issues/278) to query the same relationship multiple times with different independent criteria.

Anyway, lots more to come when I get the time to iterate on this properly, I'm sure... but those are the things that come up initially.

**Comment by pospi** [comment]
In response to queries from https://github.com/valueflows/valueflows/issues/447 -

- '@Package' has not much significance, it's just an autogenerated doc comment. I think it's nice to have those so that if files end up copied into other locations it is clear where they originated.
- Getting rid of the 'starting point' part of queries- sounds like a great idea.
- I have seen no such singular / plural *standardisation* for relationships in GraphQL, but I did some quick searching and it seems like plurals are preferred for fields that may return multiple results, by convention. Some frameworks even have special stuff to define special plural names for different words.
- IDs are `ID`. There's something called the "node API" that I have yet to implement, but the idea is to have a resolver for them that is globally unique so that nodes can be fetched directly for re-querying parts of a result without having to traverse the whole input query.
-

**Comment by pospi** [comment]
Continued wrapping up common definitions today. It seems as though you can't avoid field duplication in GraphQL without using some language with variable substitution to generate the schemas. It's kindof lame, but also kindof nice in that it forces you to declare all fields for every type each time (so viewers never have to comprehend the type resolution algorithm and hunt for definitions); and it still validates that all fields present in your base `interface`s are declared in derived types, which is what you need with this.

**Comment by fosterlynn** [comment]
>It seems as though you can't avoid field duplication in GraphQL without using some language with variable substitution to generate the schemas.

Example?  Sorry, not following.  What are you thinking of generating the schemas from?

**Comment by pospi** [comment]
I'm not, at the moment; but I was thinking of doing it within nodejs. I'd just rather have flat files which are easy for other systems to integrate directly, if at all possible.

Take a look at `Person`, say. Even though it inherits from `Agent`, you still have to define all the `Agent` fields within `Person`. It's not DRY, but the compiler does enforce that you did the duplication correctly. One of their basic design goals is to be as easy to read as possible, and having to follow an inheritance hierarchy hinders that.

Anyway, all questions here now answered or dealt with elsewhere.
