### ISSUE TITLE
Decide on spec for record subscriptions API & implement as optional schema mixin

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#50]
These are a new root-level query type with their own resolvers that return subscriptions via Apollo [PubSubEngine](https://github.com/apollographql/graphql-subscriptions/blob/master/src/pubsub-engine.ts) interfaces.

We need to decide on what the appropriate subscription names are for listening to different record updates, and what the most ergonomic way of integrating these with other query results is.

**Comment by pospi** [comment]
More info: https://www.apollographql.com/docs/apollo-server/features/subscriptions/

This might shake out naturally as part of https://github.com/holo-rea/holo-rea/issues/47

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/50.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
