### ISSUE TITLE
Setup build system for reference website & publish

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#51]
The easiest way to do this would be to modify the [GraphQL Voyager](https://github.com/APIs-guru/graphql-voyager) UI to be built as a static site rather than using the express middleware, and deploy that on a `gh-pages` branch. We'd need to:

- modify the setup to use `react-scripts` and the raw Voyager [React component](https://github.com/APIs-guru/graphql-voyager#using-as-a-dependency) instead of `graphql-voyager/middleware`
- setup a static build of the schema introspection query via some of the `graphql-tools` [utilities](https://blog.apollographql.com/three-ways-to-represent-your-graphql-schema-a41f4175100d) (see `graphqlSync`)
- setup a static build of the site with `react-scripts` which also inlines the introspection query result

@fosterlynn @bhaugen does this sound like (at least a part of) the correct course of action to you? Then that UI can be published to valueflows.github.io/vf-graphql and linked to from the main site as needed (you can preview with `npm start` by navigating to http://localhost:3000/viewer).

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/51.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
