### ISSUE TITLE
Proposal: removing unnecessary attribute naming context

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#62]
Personally I find the property names of the `owl:time` and `om:measure` generic record attributes to be unnecessarily verbose and "weird sounding" in the context of a GraphQL query API.

One of the key properties of GraphQL as an abstraction is an extremely robust, declarative binding between a UI element and a *particular* API structure. The conceptual model is that "the API" is a logically singular, distinct entity which has complete and total control over the data structures that it chooses to represent. As such, namespacing is generally considered "server-universal"&mdash; that is, every GraphQL schema is considered a unique and independent address space in of itself. They are not considered to be composed of multiple address spaces and schemas as with semantic web linked datasets.

So, I would advocate that the "`has`" prefix be stripped from `hasPointInTime`, `hasBeginning`, `hasEnd`, `hasNumericalValue` & `hasUnit`. The reality is that an attribute mapping will be necessary in all translations from the GraphQL data model to the RDF data model *anyway*, because `EconomicEvent` actually maps to `vf:EconomicEvent` etc.

Thoughts?

**Comment by pospi** [comment]
Slight update to this: I'd probably advocate for simply changing `hasNumericalValue` to `value`. We don't need the field to say "numeric" in it- it's a float, it can't *not* be numeric...

**Comment by fosterlynn** [comment]
If we do that, we are basically deciding that we are not re-using other existing vocabularies.  Or if we make the graphql naming different than the base VF naming, we are setting it up for people to be confused, have a harder time remembering names, or go to extra work in the mapping.  

So I think we should just use what it is, except for exceptionally bad situations (which is how I felt about inXSDDateTimeStamp, which we worked around by "legal" means on the rdf side).  If it is understandable (and people do spend a lot of time on these definitions), then I think it is acceptable.

**Comment by pospi** [comment]
I see where you're coming from, but I still think you're carrying over ideological positions from the semantic web world.

> we are basically deciding that we are not re-using other existing vocabularies

I don't see that as true. We're only explicitly stating that the mapping between other vocabularies and GraphQL APIs is pre-defined; which it is already. You can't "re-use other existing vocabularies" in a GraphQL server because that is not a feature that GraphQL supports. (This is what I mean by my "*particular* API structure" paragraph...)

> we are setting it up for people to be confused, have a harder time remembering names, or go to extra work in the mapping

Maybe... couldn't we solve this problem by including references to the OWL time spec and OM in the attribute descriptions? Personally the inconsistent naming format between these properties and others is something that I also find confusing.

**Comment by fosterlynn** [comment]
>Personally the inconsistent naming format between these properties and others is something that I also find confusing.

Yes, understandably.

>We're only explicitly stating that the mapping between other vocabularies and GraphQL APIs is pre-defined; which it is already. You can't "re-use other existing vocabularies" in a GraphQL server because that is not a feature that GraphQL supports.

There are definitely a bunch of trade-offs, and honestly I don't know which is best.
* we could not re-use existing vocabularies on the rdf side - this is actually what most people do, they just re-name the same concepts, and I more and more understand why - on the other hand, it seems like at a high level we want to promote reuse in vocabularies, semantic web or not
* we could change names that are inconsistently formatted just on graphql or just on json-schema or both, but leave them on the semantic web side - on the other hand then the vocabulary is different in different technologies/formats, and there will be more and more of those
* we could just use one vocabulary everywhere, opting for re-use, and know that we will have the ongoing annoyance of naming that we think isn't the best and/or isn't consistent within the vocabulary

>I see where you're coming from, but I still think you're carrying over ideological positions from the semantic web world.

Yes I am.  But I don't think ideological (I am not really a personal fan), more we need to support both the semantic web and other stuff, graphql among them.  And people will use both semantic web and graphql in some apps, so they are not actually separable even in people's individual experience.  And a lot of standardization is coming out of the semantic web, as is VF historically as a collective endeavor.

For me, the most important is that the vocabulary should be the same in all formats, with the naming and defining standing above the technical implementation.  I wouldn't mind going back into the rdf version and making it all our vocabulary, we have run into lots of annoyances trying to do re-use, besides the one you have now.  But that would be a lot of change, and this doesn't seem like a good time for that.  So my opinion would be we stick with what it is for this round, sorry you are on the receiving end as we wind our way through all of this.  I am totally good with revisiting it in a larger discussion after this round of implementations, where we said we were more or less freezing it.

**Comment by pospi** [comment]
Ok, fair enough. I do see where you're coming from and I am happy to let the longer names sit for the moment. I am just trying to get all the name changing churn / checking out of the way early to avoid time-costly changes in future.

Why are you saying this though?

> we could not re-use existing vocabularies on the rdf side

I'm not advocating any changes to the RDF at all- just the GraphQL. And I also want to assert that no direct translation is possible, even now- because the destination fields in RDF have schema prefixes and those aren't part of the field names. So whether we have to say `hasPointInTime => owl:hasPointInTime` or `pointInTime => owl:hasPointInTime`... we are still going to have to say it.

> then the vocabulary is different in different technologies/formats, and there will be more and more of those

As above: it already is. No automatic mapping would be possible except by some fairly advanced tooling that may or may not yet exist heh

**Comment by fosterlynn** [comment]
>No automatic mapping would be possible

Yeah, the analyst view vs the dev view. :)  But beyond the machine, for devs and even for users where the vocabulary is exposed directly, which I think will happen, it seems like we are adding confusion if the names are different in different technologies/formats.  But I will say I suspect @elf-pavlik agrees with you, although approaching it from the other direction.

P.S. In python if I remember correctly you would just split the string using ":" and remove the first element?  VF itself won't have any duplicates in different namespaces.

**Comment by pospi** [comment]
Sounds about right RE python. But that only works for converting from RDF to other formats; to convert back you would need to provide the mapping.

Anyway, will close this for now because everybody with opinions now knows this discussion has taken place (;
