### ISSUE TITLE
Resolve logic for ResourceSpecification / EconomicResource units

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#64]
There was some stuff in VF0.3 that used `ResourceSpecification.unitOfEffort` to infer things about `EconomicResource.unitOfEffort` upon resource creation. Those things went away in VF0.4 as the attribute moved to `RecipeResource.unitOfEffort`, but then it was impossible to determine the default units for a resource without the *recipe* module, and that didn't seem adequate.

Since the expectation for these release(s) was mostly to use `unitOfEffort` as a UI hint, we opted to re-add `ResourceSpecification.defaultUnitOfEffort` to the Holochain implementation in order to not rethink the logic and purpose of these fields too much. Thus it was re-added to the GraphQL spec in `0.4.3`.

Some work needs to be undertaken in VF core in order to determine the final path for this field, until then it remains in the GraphQL spec but not in the RDF; and this inconsistency remains to be resolved.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/64.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
