### ISSUE TITLE
Polish schema compilation process

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#67]
There are some rough edges around #61 that could be worth adding.

- [ ] infer from `@depends` tags in file header comments and throw warnings if dependant modules are not specified
- [ ] create a CLI script to generate SDL schema files from dynamic combinations of schema modules

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/67.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
