### ISSUE TITLE
Use `extends` syntax in bridging schema modules

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#68]
As of June 2018 GraphQL supports extending types with other fields, which would make the schemas in `schemas/bridging/` more idiomatic in the way they're written. Would be worth doing this, if the merging logic being used supports the changes.

Further reading https://stackoverflow.com/a/56204966

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/68.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
