### ISSUE TITLE
Investigate generating RDF / TTL schema from GraphQL

### ISSUE THREAD

**Issue by tommycp3** [valueflows/vf-graphql#7]
Bridges between GraphQL and RDF Short Paper
[https://www.w3.org/Data/events/data-ws-2019/assets/position/Ruben%20Taelman.pdf](https://www.w3.org/Data/events/data-ws-2019/assets/position/Ruben%20Taelman.pdf)

W3C just had an event on this 4th March 2019: [https://www.w3.org/Data/events/data-ws-2019/schedule.html](https://www.w3.org/Data/events/data-ws-2019/schedule.html)

Here is the records to the discussions: [https://docs.google.com/document/d/1yveIHGpxn49Ke90xX1DSuAK7CTGLgCVnaZN1q9k9H28/edit#](https://docs.google.com/document/d/1yveIHGpxn49Ke90xX1DSuAK7CTGLgCVnaZN1q9k9H28/edit#)

**Comment by pospi** [comment]
If we can generate the RDF and Turtle files from the GraphQL, it may somewhat obviate the need to maintain multiple flavours of the schema.

**Comment by fosterlynn** [comment]
@tommycp3 thanks for the links, will take a look!

**Comment by almereyda** [comment]
Meta: I have updated the OP to reference the correct links. URLs and a small url string were swapped within the bracket pair []().

Back on subject: Since GraphQL is the internal data model of the more current Value Flows implementations, the reverse will be an unlocker to extend federation to Value Flows data stored in Solid applications, such as https://lab.allmende.io/solidbase/solidbase/.

**Comment by almereyda** [comment]
Ruben from above continues in direction of GraphQL-LD. Maybe ideas developed for https://github.com/rubensworks/graphql-to-sparql.js and https://github.com/rubensworks/sparqljson-to-tree.js can be mobilised here?

I'm wondering if we should approach said person. The idea could be to ask for ideas for implementation of serializers from a `tree-json` document (a `sparql-json` result-set transformed to resemble the schema of the GraphQL query) into JSON-LD - and from there into other RDF serializations.

For an adjacent prototype to SolidBase, it appears possible to think about using GraphQL on top of LDP/Solid with https://github.com/rubensworks/GraphQL-LD-Comunica-Solid.js, and thus also have a chance to reuse and collaborate on the `vf` implementation here.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
