### ISSUE TITLE
Provide ability to inject custom schema extension modules

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#70]
The new schema modules & build system provide a way to specify and implement functional components of the spec independently. What they don't yet provide for is an ability to extend the core schema with third-party fields and relationships.

We should be able to provide additional parameters to `buildSchema` as SDL strings to merge into the final generated schema, to allow for domain-specific systems to introduce additional record fields.

**Comment by fosterlynn** [comment]
This sounds important for people like you who are using vf-graphql directly in your code!  Part of figuring out how to be a framework? :heart:

**Comment by pospi** [comment]
Already done!
