### ISSUE TITLE
Finish schema documentation

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#71]
https://github.com/valueflows/vf-graphql/pull/69 made huge progress; now the input type documentation is to an equivalent standard to the query types, and that helps greatly since these are generally the first structs newcomers encounter in GraphQL playgrounds (they have to create data before they can query it!).

There are still some holes that it would be good to have coverage on:

- [ ] top-level query methods
- [ ] top-level mutations: mutation & parameter descriptions (only fields are currently documented, not types)
- [ ] input types (again, only fields are documented- not the structs themselves)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/71.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
