### ISSUE TITLE
Agree on API for agent inventory queries

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#72]
I want to start logging these here to loop in @ivanminutillo as I work through porting Shroom to work on the latest `vf-graphql` spec. So far it has been minor things like allowing string IDs (in addition to integers) but it will quickly become a discussion about which queries are optimal and easiest to build UIs on top of.

I began with the inventory section of the app. Shroom has `Agent.ownedEconomicResources(category: INVENTORY)`. Here the closest we have is `inventoriedEconomicResources()`.

So the first question is, how to split this up? Separate methods for "owned", "inventoried", "onhand"; or a single query edge for `Agent.economicResources` that includes a category filter as one of its criteria?

**Comment by fosterlynn** [comment]
I can answer some of this.  There isn't really an "owned" any more, that is basically the `primaryAccountable`.  And conceptually the accountingQuantity relates to the primaryAccountable agent, so showing inventory in the current sense of ownership happens there.  But, I think that agents who have current custody of a resource also may have some kind of inventory needs, like a shipper reporting all of what is in the truck, or the status of a resource in transit.  That is the `onhandQuantity`.  

> Separate methods for "owned", "inventoried", "onhand"; or a single query edge for Agent.economicResources that includes a category filter as one of its criteria

I like separate queries, maybe "inventoried" and "onhand".  Or do you think this is too far from our current style of keeping the queries basic and using parameters?  I'm fine with either actually.  @ivanminutillo it might be interesting to map this to Reflow requirements and see what makes more sense there.

In terms of Shroom, I think you could use `inventoriedEconomicResources` and use `primaryAccountable` to filter.

**Comment by pospi** [comment]
Good to know which fields to filter on. I think I'll keep to using enum types for querying distinct sets of sub-records, though. Which makes this...

```gql
enum ResourceCustodyType {
  ACCOUNTABLE_FOR
  ON_HAND
}
input agentResourceSearchParams {
  searchString: String
  custodyType: ResourceCustodyType
  specificationIn: [ID!]
  classificationIn: [URI!]
  trackingIdentifierIn: [String!]
  productBatchIn: [ID!]
  effortQuantifiedIn: [ID!]
  activeProcessStageIn: [ID!]
  stateIn: [String!]
  containingResourceIn: [ID!]
  containsResourceIn: [ID!]
}
```

We probably also need a standard set of date filter parameters for querying against record authoring & update times.

**Comment by fosterlynn** [comment]
>enum ResourceCustodyType {
  ACCOUNTABLE_FOR
  ON_HAND
}

To make sure this is clear, most "accountable for" resources will also have "onhand" quantities.  I suppose for most resource, those will be the same almost all the time.  Or, there are use cases like if an agent is lending out things (say a library), usually onhand will be = or some less than accountable for, which would be the total number of copies of a book or whatever.

**Comment by pospi** [comment]
Ah, gotcha. Those are probably not query fields then but rather they would just factor in to quantity filtering and returned resource quantity data?

**Comment by pospi** [comment]
@ivanminutillo @mayel I'm curious whether we could re-open this question, specifically in terms of designing the per-agent queries needed to fetch inventory in CommonsPub. Are there existing inventory pages wired up to the backend already?

**Comment by mayel** [comment]
We haven't yet started to implement inventory.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/72.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
