### ISSUE TITLE
Agree on API for agent process queries

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#74]
I think this used to be `Agent.agentProcesses`- I think it makes sense to just call it `Agent.processes`, unless there is some better semantic meaning we can give this? (maybe `Agent.involvedInProcesses` or similar?)

Also curious as to the query logic for loading these up.

**Comment by fosterlynn** [comment]
>I think this used to be Agent.agentProcesses- I think it makes sense to just call it Agent.processes

Agree, and same for all of them, that was not the best standard.

>Also curious as to the query logic for loading these up.

Very odd, can't find the underlying logic in the old code.  But we can think about it.  If we want to find all processes related in any way to any agent, either person or organization, it would be something like: 
* all process for which the agent is the scope
* all process for which the agent is provider or receiver on an economic event or commitment or intent

Anything I might be missing?

A note - the old code has `finished` as a parameter, so you can get all finished, all unfinished, or just all.  Probably dates would be good too.

**Comment by pospi** [comment]
This one seems potentially relevant, but complex to implement:

- all process for which the agent is a member of a group which is the scope

Proposing the following for now:

```gql
enum ItemFinishedStatus {
  UNFINISHED
  FINISHED
}
input agentProcessSearchParams {
  searchString: String # searches both name & note
  name: String # searches name only
  plannedStartOnOrBefore: DateTime
  plannedStartOnOrAfter: DateTime
  plannedEndOnOrBefore: DateTime
  plannedEndOnOrAfter: DateTime
  finished: ItemFinishedStatus
  processSpecificationIn: [ID!]
  processClassificationIn: [URI!]
  inputEventsIn: [ID!] # matches if ANY of the provided IDs match to ANY input event IDs
  outputEventsIn: [ID!]
  unplannedEventsIn: [ID!]
  involvesEventIn: [ID!] # matches if any specified events are linked to the process in any way (inputs, outputs or unplanned)
  plannedWithinIn: [ID!]
  nestedInIn: [ID!] # yes, sounds silly. But technically correct & descriptive, right?
}
```

**Comment by fosterlynn** [comment]
>nestedInIn: [ID!] # yes, sounds silly. But technically correct & descriptive, right?

You don't need both In's imo. 

I'm not sure there are reasons for all of those parameters, but maybe.

**Comment by fosterlynn** [comment]
>This one seems potentially relevant, but complex to implement:  all process for which the agent is a member of a group which is the scope

Maybe we need a discussion of if to implement all "potentially relevant" queries now?  I think we should be more iterative, as you probably know by now. ;)  Better to get it all out there, and be working with people developing apps using this.

**Comment by pospi** [comment]
Sounds good, let's chat with Ivan & Mayel about their use cases and see which functionality is common. It's easy to extend the schema with custom search parameters as needed now, so that might be a good avenue to work through until we get to agreement.

**Comment by pospi** [comment]
Closing this issue to defer it for now; we'll approach these questions in a much more piecemeal manner.
