### ISSUE TITLE
Merge with `economic-sentences` GraphQL plugin

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#8]
@luandro's [economic-sentences](https://github.com/open-app/economic-sentences-graphql) GraphQL plugin not only connects Scuttlebutt to a ValueFlows API, but also has a pretty good & accurate working schema for the ValueFlows spec. We should compare these with the state of our efforts and merge the work together (:

**Comment by fosterlynn** [comment]
@pospi thanks for this!  And @luandro I didn't know you were implementing already!  This is very cool!  Very glad you guys got to meet each other and chat!

>We should compare these with the state of our efforts and merge the work together

Yes, let's figure out how to do it.  So we have a graphql reference started here.  And I think ssb uses json schemas to define their message types?  And does the plugin Luandro is using do that translation?  The [schemas](https://github.com/open-app/economic-sentences-graphql/blob/master/schema/typeDefs.js) look more or less like json schemas, maybe without some header info?

**Comment by luandro** [comment]
Thanks @pospi! I've been using it to start playing around with [community bots](https://github.com/open-app/bazaar-bot) @fosterlynn. I've made simple uses of VF so far, but it's a start.

> ssb uses json schemas to define their message types?

Correct!

> And does the plugin Luandro is using do that translation? 

It basically creates the appropriate messages, and posts them to SSB. Count with me for the necessary changes needed to merge our efforts 👍

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/8.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
