### ISSUE TITLE
Design per-agent intent & commitment query API

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#82]
Based on comments @fosterlynn has [previously made](https://github.com/valueflows/vf-graphql/issues/73#issuecomment-596644499), there might be some complexity involved in the logic for querying intents for the offers & needs UI.

Are there some existing queries in the CommonsPub UI that we can pull into the core spec for standardisation?

**Comment by mayel** [comment]
I'm not aware of any changes needed now, but happy to add queries that make sense or that we realise are needed based on UX designs.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/82.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
