### ISSUE TITLE
Standardise querying of date fields

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#83]
We've had a bit of a discussion of this in #75 & #15 which got far too complicated far too quickly. I know others have opinions on handling date-based queries and I think I can summarise a few of them, so let's see:

- two search parameters, `startDate` and `endDate`, should be sufficient
- `startDate` and `endDate` can be provided as either ISO8912 dates or as date+time+seconds; "start" will be taken as the beginning of the interval and "end" as its conclusion
    - eg. `startDate = 2020-10-02, endDate = 2020-10-02` returns all records between `2020-10-02 00:00:00` and `2020-10-03 00:00:00`
- for simplicity, we should match only on `hasPointInTime` and `hasBeginning`, and ignore `hasEnd`
- results should always be returned in chronological order

Thoughts on this as a general approach going forward?

**Comment by mayel** [comment]
I'd tend to be pretty flexible with query parameters (so maybe a string that the backend can transform into a date/time). 

What we do have to standardise is how dates appear in results. Currently in CommonsPub the DateTime scalar type represents a DateTime value as specified by ISO 8601.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/83.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.

**Comment by pospi** [comment]
Some implementation work on this has been done in https://github.com/dyne/reflow-os/issues/16#issuecomment-964851810 that should be considered in the final spec.
