### ISSUE TITLE
Standardize paginated queries

### ISSUE THREAD

**Issue by mayel** [valueflows/vf-graphql#84]
This is the approach we currently take with CommonsPub, it would be good if we could standardise to use compatible queries between apps:

`type IntentsPage {
edges: [Intent!]!
pageInfo: PageInfo!
totalCount: Int!
}`

`type PageInfo {
endCursor: [Cursor!]
hasNextPage: Boolean
hasPreviousPage: Boolean
startCursor: [Cursor!]
}`

Cursor is a scalar defined as an opaque position marker for pagination. Paginated queries return a PageInfo struct with start and end cursors (which are actually lists of Cursor). You can then issue queries requesting results before the start or after the end cursors to request the previous or next page respectively.
It's actually a string or integer. May be extended in future.

**Comment by mayel** [comment]
What do you think @pospi

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-graphql/-/issues/84.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
