### ISSUE TITLE
time & interval representations

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-graphql#9]
Just wanted to create an issue for this so we can track it.

There is an ISO8601 spec for both timestamps [and intervals](https://en.wikipedia.org/wiki/Iso8601#Durations), so I think we just define `DateInterval` to the spec, and rely on the time handling capabilities of the underlying language to parse values.

Any objections to this being the standard behaviour for all GraphQL APIs going forward? @sqykly @luandro @ivanminutillo @fosterlynn

**Comment by pospi** [comment]
See also https://github.com/valueflows/vf-graphql/commit/85bab9b97a21e2b72b5b34995835904b60512c4c

**Comment by fosterlynn** [comment]
For discussion's sake, we have been working with this time standard: https://www.w3.org/TR/owl-time/.  Although we haven't settled exactly on how to use it, handling either a duration or an instant.

I'll take a closer look and see what the differences are, I expect they are very related.  Will report back here.

I assume that ISO standard is free and open?  Some of them aren't, like the quantities / units of measure (grrrrr).

**Comment by pospi** [comment]
>
> I assume that ISO standard is free and open? Some of them aren't, like the
> quantities / units of measure (grrrrr).
>
Yeah, and I'm pretty sure we could just define a union type for fields
which are able to accept either form of time input. I thought they were all
one or the other, silly me...

**Comment by fosterlynn** [comment]
Well the full ISO 8601 standard is for sale.  But doesn't really matter so much, since it is all over the web anyhow.  Also I think I have determined that the ISO 8601 format is the same as the XSD format, which is used in some of the attributes in the owl standard we are using.  So, I'd suggest we stick with the owl spec (link above) and use the XSD attributes.  Will do a bit more gathering of the discussions and examples over in VF repo and make a PR over there - will ping you @pospi .

**Comment by fosterlynn** [comment]
> Will do a bit more gathering of the discussions and examples over in VF repo and make a PR over there

We have some conclusions in VF.  The question is how to make them work for graphql and other non-rdf representations.

In VF, we are using the owl time spec to represent the times on intents, commitments, and economic events.  Right now that includes hasBeginning, hasEnd.  And Process.duration uses owl time TemporalDuration.  (Looking now, probably should be Duration. And any other time representation we need will be from somewhere in the owl time spec.

For reference again, here is the owl time spec, look at the first diagram in this section https://www.w3.org/TR/owl-time/#topology.  And for Process.duration, look here https://www.w3.org/TR/owl-time/#duration.

In intents, commitments, events, seems ok to me to use hasBeginning and hasEnd.  We also need at least a time that is an instant, unless we will make people put the same time in beginning and end, which is one possible solution.  In owl time the one that would work for us is called inXSDDateTimeStamp, because it uses the same format as ISO8601.  But I'm not putting that name in graphql, or anywhere actually in the VF vocabulary.  Ouch!

So, the first question is: what do we want in the graphql reference, starting with the instant?  Could be `hasTime` (or some name to represent the Instant rather than the TemporaEntity).  In the VF doc, we are also currently referencing hasDuration, before, after, intervalDuring as elements from another vocabulary we think people might use in VF applications.  This is not a completely solid list, could be more, could be less.

We could just have the 3 named fields hasBeginning, hasEnd, hasTime, ignoring Process for the moment.

Or we could do something like I did for QuantityValue, and define a piece of owl time as a separate type(s) with just the limited fields we want to use, possibly modified to not be talking about XSD.

[edit] Or we could do something I haven't thought of that makes sense in the graphql world.

I'm looking for some discussion on this @pospi so that I can get to some initial conclusions hopefully in the next week.... thanks!

**Comment by fosterlynn** [comment]
Tracking time:inXSDDateTimeStamp, it references dateTimeStamp in the owl xml datatypes spec https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp.  Maybe we can do something with that, I could maybe live with `dateTimeStamp` as a property, although it certainly isn't perfect.  I'm pretty sure it also has the same formatting as the ISO one.  Hmmmm.

**Comment by pospi** [comment]
Don't have much space to go deep into this right now, but on surface level it all looks sensible. As long as we're building to an existing spec I am pretty happy. It does seem like `owl-time` includes a lot of different formats, and if possible it would be nice to use only a subset of them if we can do so and maintain the flexibility we need- it will just be easier for implementers if they don't have to do things like implement Gregorian calendar offsets in addition to ISO8601 date strings...

Suggest the field names in GraphQL just strip the `inXSD` prefix for the most part?

**Comment by fosterlynn** [comment]
Tracking time:inXSDDateTimeStamp, it references dateTimeStamp in the owl xml datatypes spec https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp.  Maybe we can do something with that, I could maybe live with `dateTimeStamp` as a property, although it certainly isn't perfect.  I'm pretty sure it also has the same formatting as the ISO one.

>It does seem like owl-time includes a lot of different formats, and if possible it would be nice to use only a subset of them if we can do so and maintain the flexibility we need- it will just be easier for implementers 

I totally agree!

I'm leaning atm towards doing it sort of like we do QuantityValue (from the QUDT vocabulary) and fudging even a bit more than that.  Would give us:

* property `hasTime` referencing a TemporalEntity.  TemporalEntity would include the following plus maybe a couple more that we could run into in the next months:
     * hasBeginning
     * hasEnd
     * before
     * after
     * dateTimeStamp  (or even I'd be fine with a better name)

* property `hasDuration` referencing a Duration, which would include:
     * numericDuration
     * unitType

**Comment by pospi** [comment]
What's the related VF issue to track this? [#460](https://github.com/valueflows/valueflows/issues/460)? It looks like the properties in the TTL reference file are in an island at the moment and haven't been linked to any of the VF records. Also a bit unclear on how it all works with `propertyChainAxiom`- haven't encountered that before.

I'm not sure I like having `TemporalEntity` as a catch-all structure for this. I would prefer that the records containing time fields are more explicit at the top level as to what kinds of `TemporalEntity`s they are expecting. For example:

- since `Transfer` is always a single point in time, it should just keep the ISO8601 `DateTime`, but we might want to rename the field from `plannedTime` to `hasTime` to fit the [OWL spec](https://www.w3.org/TR/owl-time/#time:hasTime).
- things like `RecipeProcess` which only have a duration should use the ISO8601 duration format only (seems to be as-is, though I may rename our GraphQL `DateInterval` scalar type to `TimeDuration` or turn it into an object type with `numericDuration` & `unitType` - your preference?)
- for event / commitment / intent, I think we only need `hasBeginning` & `hasEnd` or `hasTime` (better name than `dateTimeStamp`?) in order to service all needs. `before` and `after` look like attributes for relating different `TimeInterval`s to each other, which isn't something we need to do (unless I've missed something).
- `Process` looks like it needs some work. Currently only has a timestamp but expect it needs to be able to carry intervals as well.

So this leaves us with a set of appropriate field names, where values are either ISO8601 `DateTime` or this `TimeDuration` struct/scalar. No other crazy parsing needed- I don't think we need to be able to define intervals in terms of a bound & duration- start & end times are easier to reason about.

Not sure where this leaves repeating intervals- are those needed in some cases?

**Comment by fosterlynn** [comment]
>What's the related VF issue to track this? #460? 

Also here https://github.com/valueflows/valueflows/pull/470

> It looks like the properties in the TTL reference file are in an island at the moment and haven't been linked to any of the VF records. 

Yeah, the ttl file will be missing important things if they are from another rdf vocabulary, which makes the graphql and json-schema references very important imo (as well as the UML).

>Also a bit unclear on how it all works with propertyChainAxiom- haven't encountered that before.

I don't understand the technicalities either, @elf-pavlik came up with that to give us a way to tunnel into the owl time spec, with similar names.  Lots of discussion on all of that as we attempted to make it work for rdf and non-rdf.

>I would prefer that the records containing time fields are more explicit at the top level as to what kinds of TemporalEntitys they are expecting.

We can look at that in detail, and I agree if we can limit them, we should.

>since Transfer is always a single point in time, it should just keep the ISO8601 DateTime, but we might want to rename the field from plannedTime to hasTime to fit the OWL spec.

We ended up with vf:hasPointInTime for the instants.  Transfer should be that, although Transfer may go away, long story there still under lots of discussion.

>things like RecipeProcess which only have a duration should use the ISO8601 duration format only (seems to be as-is, though I may rename our GraphQL DateInterval scalar type to TimeDuration or turn it into an object type with numericDuration & unitType - your preference?)

Preference: `Duration` with `numericDuration` and `unitType` (to match the owl time spec).  OK?

>before and after look like attributes for relating different TimeIntervals to each other, which isn't something we need to do (unless I've missed something).

These are pretty useful in commitments, when you need to have something done `before` some date-time (not worrying about it being another temporal entity, just using the ISO formatted date-time thing we are using for instants).  Less useful in event, but still it happens, especially with before, if it doesn't matter for coordination, people tend to just say they spent x hours before the end of the month on a monthly task.

>Process looks like it needs some work. Currently only has a timestamp but expect it needs to be able to carry intervals as well.

Yeah, looks like I didn't finish it. :(  Will take a look, thanks for catching it.  Probably only needs the interval, hasDuration.

**Comment by elf-pavlik** [comment]
> before and after look like attributes for relating different TimeIntervals to each other, which isn't something we need to do (unless I've missed something).

Especially for planning people may prefer to use [Topological temporal relations](https://www.w3.org/TR/owl-time/#topology) rather than precise *hasBeginning* and *hasEnd*. 

> Process looks like it needs some work. Currently only has a timestamp but expect it needs to be able to carry intervals as well.

I consider process as temporal entity just as flow so beside *hasBeginning* and *hasEnd*, one can also use *Topological temporal relations* to describe its temporal aspect in relative way.

> We ended up with vf:hasPointInTime for the instants. Transfer should be that, although Transfer may go away, long story there still under lots of discussion.

To stay precise we just use `time:inXSDDateTimeStamp` property directly to relate instant with ISO8601 timestamp (`xsd:dateTimeStamp` - data type). We discussed `hasPointInTime` just as local alias which reference JSON-LD context would provide. `vf:` namespace doesn't actually include it since `time:` already includes exactly what we need.

**Comment by fosterlynn** [comment]
>>What's the related VF issue to track this? #460?

>Also here valueflows/valueflows#470

Also https://github.com/valueflows/valueflows/pull/453 and https://github.com/valueflows/valueflows/pull/485.  But lots of confusing history to just read it, I guess.

**Comment by fosterlynn** [comment]
From https://github.com/valueflows/valueflows/pull/485#issuecomment-481233849

>I think instead of defining owl:equivalentProperty you can just choose your local alias eg. occuredAt and JSON-LD context can map "occuredAt": { "@id": "time:inXSDDateTimeStamp", "@type": "@vocab" }, this keeps bridge between implementations fully aware about underlying globally unique IRIs and implementations relying on local aliases (not globally unique strings).

And above

>To stay precise we just use time:inXSDDateTimeStamp property directly to relate instant with ISO8601 timestamp (xsd:dateTimeStamp - data type). We discussed hasPointInTime just as local alias which reference JSON-LD context would provide. vf: namespace doesn't actually include it since time: already includes exactly what we need.

@elf-pavlik I don't think we ever got hasPointInTime into the json-ld context.  We can do it that way for now, but I'm still not comfortable with the "local aliases" statement. I think we do want vf:hasPointInTime to be a globally unique string, same as vf:hasBeginning and vf:hasEnd, even though it will work as non-global in graphql - true @pospi ?  (More and more I understand why rdf vocabularies don't re-use other rdf vocabularies for their critical items, and just define equivalency.  I think we are the exception.  After we get through more pressing priorities, I'll file an issue so we can discuss it again in one place.)

>I'm not sure I like having TemporalEntity as a catch-all structure for this.

That is also part of the same discussion.  In any case, I think we can proceed without it in the graphql reference.  (And I agree that for something like an economic vocabulary, people need to know as specifically as possible how they can reliably communicate with other apps, even in the more open world of semantic web.  But also, as usual, more examples will help.)

Sorry for hijacking this repo. :)

**Comment by fosterlynn** [comment]
>I'm not sure I like having TemporalEntity as a catch-all structure for this.

Was just thinking that maybe when we had our training @pospi we still had TemporalEntity in the UML... if so, sorry for the confusion, but it is gone now.

**Comment by pospi** [comment]
Confirming that implementation is done in a 'non-global' way in GraphQL when applying common properties to records.

And I understand the use-cases for temporal relation types now, thanks! (:

**Comment by pospi** [comment]
Should `ExchangeAgreement.agreedTime` & `Claim.created` be changed to `hasPointInTime`, or are those fields conceptually different?

Related: should each record include CRUD metadata; i.e. `createdTime: DateTime` & `createdBy: Address`?

I've applied some updates based on @fosterlynn's above comments. I think we're now in a position where all the relevant records include the necessary flexibility to define bound & unbound ranges, instants & before/after constraints. What they don't do is *repeating* intervals, which for me tends to make sense (you'd generally want to repeat the processes & events themselves rather than their timing data, right?)

**Comment by fosterlynn** [comment]
>Should ExchangeAgreement.agreedTime & Claim.created be changed to hasPointInTime, or are those fields conceptually different?

Claim.created is conceptually different than hasPointInTime imo.  We actually don't have anything on ExchangeAgreement in VF, and may just get rid of it and use Agreement, which also doesn't have any properties in VF.  If we do have agreedTime, yes it should become `created`. 

>Related: should each record include CRUD metadata; i.e. createdTime: DateTime & createdBy: Address?

Good question, I have wondered the same thing.  Have only added it where it had a need besides just debugging data, so far.  The createdBy may also relate to the onBehalfOf question?

>What they don't do is repeating intervals, which for me tends to make sense (you'd generally want to repeat the processes & events themselves rather than their timing data, right?)

Right.

**Comment by pospi** [comment]
This all looks great now. I think we're done!
